name: Automated Review

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint flake8 Flake8-pyproject pytest pytest-coverage
          pip install numpy opencv-python
      - name: Checking the code using Flake8
        run: |
          flake8 $(git ls-files '*.py')
      - name: Reviewing the code using Pylint
        run: |
          pylint $(git ls-files '*.py') --rcfile=pyproject.toml
      - name: Running unit-tests using PyTest and PyTest-Coverage
        run: |
          coverage run -m pytest  -v -s
